### ISSUE TITLE
Better way of managing multiple DB envs in config.yaml

### ISSUE THREAD

**Issue by dustine32** [pantherdb/fullgo_paint_update#1]
I know the noctua config.yaml has a good way of controlling parameters for multiple environments, only requiring that the environment name (dev, prod, etc) parameter be changed to take effect.

Need to set this up in config.yaml and update the example file accordingly.

**Comment by dustine32** [comment]
Correction, it's the noctua "startup.yaml" file to steal the idea from:
```
DEFAULT_APP_DEFINITION:
  comment: The application profile to use at startup.
  type: string
  value: minerva_local

APP_DEFINITIONS:
  comment: A list of resources that Barista will allow public access to.
  type: list
  value:
    - id: minerva_local
      target: http://68.181.125.171:6800
      public:
        - m3Batch
        - seed/fromProcess
    - id: minerva_public
      target: http://toaster.lbl.gov:6800
      public:
        - m3Batch
        - seed/fromProcess
```

So we'd have something similar to an APP_DEFINITION for Panther_test, Panther_prod, and Curation DBs. Then the db_caller.py would look at DEFAULT_APP_DEFINITION['value'] and pull the right credentials.
